apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-gateway.fullname" . }}
  labels:
    {{- include "k8s-gateway.labels" . | nindent 4 }}
data:
  Corefile: |-
    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        k8s_gateway "{{ required "Delegated domain ('domain') is mandatory " .Values.domain }}" {
          apex {{ .Values.apex }}
          ttl {{ .Values.ttl }}
          {{- if gt (len .Values.watchedResources) 0 }}
          resources {{ join " " .Values.watchedResources }}
          {{- end }}
        }
        prometheus 0.0.0.0:9153
        cache 30
        loop
        reload
        loadbalance
    }